apiVersion: v1
kind: Pod
metadata:
  namespace: myapp
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - name: app-secret
          mountPath: "/mounted-secret"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: app-secret
      secret:
        secretName: app-secret
