apiVersion: v1
kind: Pod
metadata:
  namespace: myapp
  labels:
    run: nginx
    x: y
  name: nginx
  annotations:
    pippo: pluto
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - name: app-secret
          mountPath: "/mounted-secret"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: app-secret
      secret:
        secretName: app-secret
