apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: myapp
data:
  token: ENC[AES256_GCM,data:E3Gzgd8Jz25w6scO+7ohbbsYzjXmp8D0hB5pYBdk1yVJmWfPWkiW7ZZDYePEoDFd,iv:ImnwMWmdoPp4LqHMphedjiB0n63yberh1EqabCiz+GA=,tag:U91clJCRs6L0ji9ArpTPmg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-09-19T12:28:18Z"
  mac: ENC[AES256_GCM,data:7htDO3O0CEgTGo5DIyeFIMWtudXXeVA02BhGRLdN3OjB3+95+qgQ+l4ZgBx5pNQBDMEMD4yGzWbdSog54LkwwF81j+U8oQn4kcnDSiQ65knO3eGzCzivqwcA6I1Yr1JvdovUYik+dN/A6CF+R5kv7zqxk8pPFd0o3s7B3Ol/HNU=,iv:H7wnCLhaWEMn3tl56jjSsQyRfjZA52OaZ5CNVGtjms4=,tag:vSjaA6btq1So4dX2CjSXOw==,type:str]
  pgp:
    - created_at: "2024-09-19T12:28:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----
        
        hQIMA3Sjg+qeeMWVAQ//b2rWjOuH8syNF0SJZnhQOPz5GCr3fM41mB/TOcf6bja3
        qkTz2dAbeFizmZgah58Q3qleq4NNMhmfiv5p5NuhDwXPzLE+2RJ3BvlN8V5T8UBo
        OJppP5ZpROivB337FVWWd6XH9NU6Ly+YyhQko7m3F3uNiDxeky+Nh37nvRFju8+J
        XXbENM4/HYPgSdWldL550gnlwG2+DDy1cq7EgGiXULWOWTrMBVk7/Ki1/Vb6JklL
        yg5byb4zXUQDFOIbjxhkOn0l7Qy80EcA17OKaBO5CIH/HsGBCzY1dnGK8R6Ynqs9
        UKTVi4/wo+CtQ+2f8GNLlqBQjl4ND++bwrSzFIO58cioVgir+9ktjj5xXdUwtq8L
        ED8G2eShiJmvn7YgAtP7WhHr8ZwzItKd1MIMoqaijnhCeH/1FmNJrTlJMpeGaFgc
        eeaTJ/HooVOwHSSI1Cy+YozMWw26i9bJ9PulHCqnMaARJUTeSUEy5YWskFwfi+56
        TubGINvbJ9I5eRcYdMphF31J52K/7gnWdWwjq5yvZmZeRWAuZjgO21g1dfojqYLr
        4pKxbMwSCieUYkAoMKpQd8ySXa3iM+VI3rvYrIVTCrCEf2JiBWhnGz3xGtVmac0l
        Iz1aeMc0nL1eg+1QLIs54CF+SMpCN2/5oDhD1vz3oh48tsCw7py6xqUV+K9m6QvS
        XgEpwsYW3xL1uF6AbC42OsIpYwkhFPv2QaM3jwnktPu0WWA/5b7y3TfPIxlVr5lA
        Tv02FgpYpN3VsVQNv/ilVXNTK2hTw/G8X3V1Od3zcxgPD0jjRLKY016oikOaIgo=
        =PMyL
        -----END PGP MESSAGE-----
      fp: 04FFB97586336181B913C89478CF6EC541716D90
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0