apiVersion: v1
data:
    token: ENC[AES256_GCM,data:oM6e47tfMbMHbCzsgoMiaw==,iv:VJ0vuWU/AhJZRC6PCfhTjffIFvM/wUj7N2LrfuTJ7dw=,tag:H3VQROZ8DiGGq3/1lcVJpA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: secret2.yaml
    namespace: myapp
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-25T13:13:34Z"
    mac: ENC[AES256_GCM,data:pfRCnDXyc9JqsKOGhOhX3ogLvxzBw5aVKxn1Thiucq+OTj2pJ1eSSkWDKOcbFaWpC9xQds9muDuVBGDRvOjzvpAEwGONbFlCHxWKqcvMI7XWVy2fpY2Q//IG+hvKlOJ7hYtsp3cg2QfM/ZcJkTAPQYsercaQnyJZjGl8SDOs7YM=,iv:Palzl+GnZOyviTyk4SHlGn/bWsxPnIVAo7D+K02GDWI=,tag:S6X1v05bHngktC543+28KA==,type:str]
    pgp:
        - created_at: "2024-09-25T13:13:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA393xlWGl+odARAAp7w9rDkEn/qRF0hgGIvZzZPhwv9BBuTudX7R9h1vjJHJ
            WOeJ99DjIlkzPUyB/BrW4LSWm+XAqJNy7RkmzJn7YIT8X7hS9rvUaOjiCecJMUPq
            ccu/OBpd5PuNf1WQ0iKu6x72powkF+16yeVjik3ULnu5hHF7tMojlfvkSo30CYDQ
            k+KOXN5Tq/u25s2LV88nFuvQfI5ZBggNyKRi112JcHugNG0mbMGrIz9yikpCD0pi
            WPlKsAmfosHncCDFExZ8x8yZreZV+74Gl6lulORkLzp2s7zO9fKzJg9ahScpqOWt
            05JXhoOm5WrRah1X5yCbvYgK8kr/foUVzdP0fY+HA7hLT/d3/TQdi6hgMZopcZIU
            K+2+ab+WDwtejs8fuXUAaMNW3WM7b0LK41cEsigGTYdtK3MJZNGt5ceden9bLQ49
            hZ3ABvtv4s9p/iXdrMxDbKAE8f68jhmEYtABEX8OIKxfduz/3Xd3JfeJsxVA6VBU
            uGUG8OIKazfguiiEznELVcT/lJDOQ2HlPPhQ8dKJi0XCgacXpA2+LJZ+m8nnVbrx
            r0vg317fYD+rX/PWOKtcejBTIXtLXJrfIMJemkUQd7sqmsFFF4YeubuXVdy6mDJc
            sStEEliBSA9PBvzUzQzt4UaIP9SvFEhSEPBtXTjGDPSz40WdOq+IydIlWqYKu/DS
            XgFTG5oC3xiudUpQMP8T4oXB/R84YoJbIk3XEIbU3qdN4WxKmK+CB/7fD6A+Cagf
            j/yL4mLHGsLWkb7MJwHULO4qWxaaDtnJcL3WU72eknI44fH0s6WpAWCrQ21QdH8=
            =Ru1+
            -----END PGP MESSAGE-----
          fp: 5119A1431B805AEE29CD9800DA41BF5FC5A2F8D9
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
