
apiVersion: v1
data:
    token: ENC[AES256_GCM,data:v2zx5eLA6Mjkn4Q8gOYDTQ==,iv:v3sz+woEbMtYhhwtcbrJKRDiX0j8KnXhdhpNshha/vo=,tag:fyhiCW0FcEcIwM1JkHjNrg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: secret2
    namespace: myapp
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-25T17:51:00Z"
    mac: ENC[AES256_GCM,data:2qkTd6kjOK6uBU9WUgSBf5s/ExUoqVG0sczH41l0fVIqO5JA++Fa/gOizhZTfiMIuAKAcENrqlEQ+Fps9qQWhxcqK28HU5J7tGuOb+bRVgb9uHGuCTAYmOdH5Too1epIKNkr4/2B098rlQqre1wU/QUmAYARk9zEOx7sLlVj6Ws=,iv:Z4qw2NMdLeEGK/oxBz45a/47zkY1nbJw+JO/LSMCaeA=,tag:SI4vMRyUgFbRaWiSP8J1KA==,type:str]
    pgp:
        - created_at: "2024-09-25T17:51:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA393xlWGl+odAQ//SX+lsg0Pg6JQIcYwDSqXyEPkZ25m5CGfuky9I1taZ0wh
            nKr7SFaWTa4b2r8lho9ZOpPfBuE6vi2Y8v7fZxKHVYyJP3RH0YogaiKwJPizZXTF
            CDciGLeRvVLvzjDeWzfElnFc5vl42sWutkIM8hKOYj4Xa6v89qFA1EyZuWAN7StC
            MRGHeTIdLhoN2IU6fkAHjq2uNmAdAvaI5NXpDMJCUNlQ1KYlypLGP7nbQGrUb7jp
            pY6UIvWcl/sPBIGYm0CcfuiQ4P946GI5Ad39jKbPaOQ7XY3CvY2c+yo7xpJtX7r8
            09YB8IsVZVzfUEFhdmSgR52x9mfWeI0cciPaZYNB3aQjBPMPPn4CM28mgn/A6Nbi
            bcGe0h05oAtAtYFzojEZbBMZ/VzfnstMVbP24KUAqcW5Y7cmH0XlhKtZn+8HbDKk
            WuzTaKeEOcCfTfQrHK4omqllXgJ+taz1xaWbLBMFyUBJC+wAPr/vlC5LQAdwC+iL
            r5fW6+gwHmJEh+ggAhDY8wDnlW+dnwQ+kSbr43vnXZImvEkFwl9jJMpfh9LDLq1F
            3UwJvMIXFZQBtq3NUX/mN6rFayhXZcMWbAUGXNcahDz4upU1dz/G8yrkOwGOSx1d
            W1816RTWXbHlh33fjOmMNIGx4efPvros1QODu+/B8mbvtHkCRluzi1iDYN9dRgDS
            XgGM7bKa/NfLqlOqlAZiNV8FQjrctAjuLHw1so6iNxam/LypAJ/Cej5nbN4ieK+p
            LN/YcUcAMb5gIuK1BPmLv/Gzpzxgf5W2dVd4+i2dg5aik6NWmIfLPVTh4lKg+/Y=
            =aYhq
            -----END PGP MESSAGE-----
          fp: 5119A1431B805AEE29CD9800DA41BF5FC5A2F8D9
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
